server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进eureka的服务名称
  cloud:
    config:
      server:
        git:
          #github上面的仓库名字
          uri: https://github.com/linborris/springcloud-config.git
          search-paths: #搜索的目录
            - springcloud-config
      label: master #读取的分支
  #rabbitmq相关配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest



eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
        #curl -X POST "http://localhost:3344/actuator/bus-refresh" 总线刷新，一次请求处处生效
        #curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:3355" 针对性刷新
        #curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:{3355,3366}"
