server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
    url: jdbc:mysql://49.233.204.165:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false

eureka:
  client:
    #    表示是否将自己注册进eureka-server  默认为true
    register-with-eureka: true
    #    是否从eureka-server中抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true，才能配合ribbon的负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
#  instance:
#    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

