server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**     #断言，路径相匹配的进行路由


        - id: payment_routh2
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
#          filters:
#            -AddRequestParameter=X-Request-Id,1024 #过滤工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id 值为1024
          predicates:
              - Path=/payment/lb/**     #断言，路径相匹配的进行路由
#              - After=2020-05-13T16:55:34.294+08:00[Asia/Shanghai] #在这个时间之后此配置才会生效
#              - Before=2020-05-13T16:55:34.294+08:00[Asia/Shanghai] #在这个时间之前此配置才会生效
#              - Between=2020-05-13T16:55:34.294+08:00[Asia/Shanghai],2020-05-13T18:55:34.294+08:00[Asia/Shanghai] #在这个时间之间此配置才会生效
              - Cookie=username,lzx   #验证cookie中是否含有这个kv键值对  测试方法：cmd -》curl http://localhost:9527/payment/lb --cookie "username=lzx"
              - Header=X-Request-Id,\d+ #请求头要包含有X-Request-Id属性，并且值为整数的正则表达式 测试cmd->curl http://localhost:9527/payment/lb --cookie "username=lzx" -H "X-Request-Id:12aa"
              - Host=**.somehost.org,**.anotherhost.org   #请求头中host必须为以上才能访问  测试curl http://localhost:9527/payment/lb --cookie "username=lzx" -H "X-Request-Id:123" -H "Host:www.somehost.org"
              - Method=GET   #允许get方法          curl http://localhost:9527/payment/lb?age=13 --cookie "username=lzx" -H "X-Request-Id:123" -H "Host:www.somehost.org" -X GET
              - Query=age,\d+  #验证是否包含该参数条件 curl http://localhost:9527/payment/lb?age=13 --cookie "username=lzx" -H "X-Request-Id:123" -H "Host:www.somehost.org" -X GET


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

