server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 49.233.204.165
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        health-check-url: http://112.48.59.10:8006/actuator/health
        # springboot2.0+加入下面配置
        # springboot2.0+health路径如下
        health-check-path: /actuator/health
#        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/${spring.cloud.consul.discovery.health-check-path}

management:
  endpoint:
    health:
      show-details: always